version: '2.1'

services:
 transmission:
    image: linuxserver/transmission
    container_name: transmission
    devices:
        - "/dev/net/tun"
    cap_add:
        - NET_ADMIN
    env_file:
        - stack.env
    volumes:
        # - <path to watch folder>:/watch
        - /media/${USER}/Data/downloads:/downloads
        - /media/${USER}/Data/appdata/transmission:/config
    ports:
        - 9091:9091
        - 51414:51413
        - 51414:51413/udp
        - 8888:8888
        - 8989:8989       # sonarr
        - 9117:9117       # jackett
        - 8083:8083       # calibre-web
        - 8087:8080       # calibre
        - 8086:8081       # calibre
        - 7880:7878       # radarr 7878 used by SOAP
    restart: unless-stopped

 jackett:
    image: linuxserver/jackett
    network_mode: "service:transmission"
    container_name: jackett
    depends_on:
        - transmission
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/jackett:/config
    restart: unless-stopped

 radarr:
    image: linuxserver/radarr
    network_mode: "service:transmission"
    container_name: radarr
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/radarr:/config
        - /media/${USER}/Data/downloads:/downloads
        - /media/${USER}/Data/media:/media
    restart: unless-stopped

 sonarr:
    image: linuxserver/sonarr
    network_mode: "service:transmission"
    container_name: sonarr
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/sonarr:/config
        - /media/${USER}/Data/downloads:/downloads
        - /media/${USER}/Data/media:/media
    restart: unless-stopped

 lidarr1:
    image: linuxserver/lidarr
    container_name: "lidarr-main"
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/lidarr1:/config
        - /media/${USER}/Data/media/music:/media
        - /media/${USER}/Data/downloads/soulseekqt:/downloads
    ports:
        - 8686:8686       # lidarr
    restart: unless-stopped

 lidarr2:
    image: linuxserver/lidarr
    container_name: "lidarr-gachi"
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/lidarr2:/config
        - /media/${USER}/Data/media/gachi:/media
        - /media/${USER}/Data/downloads/soulseekqt:/downloads
    ports:
        - 8687:8686       # lidarr
    restart: unless-stopped

 lidarr3:
    image: linuxserver/lidarr
    container_name: "lidarr-nederlands"
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/lidarr3:/config
        - /media/${USER}/Data/media/muziek:/media
        - /media/${USER}/Data/downloads/soulseekqt:/downloads
    ports:
        - 8688:8686       # lidarr
    restart: unless-stopped

 calibre:
    image: linuxserver/calibre
    network_mode: "service:transmission"
    container_name: calibre
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/calibre:/config
        - /media/${USER}/Data/media/books:/books
        - /media/${USER}/Data/media/books_not_in_library:/books_add_me
    restart: unless-stopped

 calibre-web:
    image: linuxserver/calibre-web
    network_mode: "service:transmission"
    container_name: calibre-web
    env_file:
        - stack.env
    volumes:
       - /media/${USER}/Data/appdata/calibre-web:/config
       - /media/${USER}/Data/media/books:/books
    restart: unless-stopped

 plex:
    image: linuxserver/plex
    ports:
        - 32400:32400
    container_name: plex
    volumes:
        - /media/${USER}/Data/appdata/plex:/config
        - /media/${USER}/Data/media/tv:/tv
        - /media/${USER}/Data/media/movies:/movies
        - /media/${USER}/Data/media/muziek:/muziek
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Brussels
    - UMASK_SET=022
    - VERSION=latest
    # - PLEX_CLAIM=claim-CYu2Y-v8qAMfN1azT3iY # https://www.plex.tv/claim/
    restart: unless-stopped

 soulseek:
    image: realies/soulseek
    container_name: soulseek
    volumes:
       - /media/${USER}/Data/appdata/soulseek:/data/.SoulseekQt
       - /media/${USER}/Data/downloads/soulseekqt:/data/Soulseek Downloads
       - /media/${USER}/Data/appdata/soulseek/chat_logs:/data/Soulseek Chat Logs
       # Shared folders
       - /media/${USER}/Data/media:/data/"Soulseek Shared Folder"
    ports:
        - "6080:6080"
    environment:
        - USER=user
        - TZ=Europe/Brussels
        - DNS=8.8.8.8,8.8.4.4
    restart: unless-stopped

 filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - 8090:80
    volumes:
      # See readme.md
      - /media/${USER}/Data/appdata/filebrowser/filebrowser.db:/database/filebrowser.db
      - /media/${USER}/Data/appdata/filebrowser/settings.json:/config/settings.json
      # Shared folders root is /srv
      # After updating folders run: rm filebrowser.db ; touch filebrowser.db ; rm -rf ~/Filebrowser/* 
      - /home/${USER}/Applications/Filebrowser:/srv
      - /home/${USER}/Documents/Share:/srv/Documents
      - /media/${USER}/Backup/Share:/srv/Backup
    env_file:
       - stack.env
    restart: unless-stopped
