name: "home-media-server-vpn"

services:
  calibre:
    image: linuxserver/calibre:7.22.0
    container_name: calibre
    volumes:
      - /media/${USER}/Data/appdata/calibre:/config
      - /media/${USER}/Data/media/books:/books
      - /media/${USER}/Data/media/books_not_in_library:/books_add_me
    env_file:
      - stack.env
    ports:
      - '0.0.0.0:8092:8080' # calibre http
      - '0.0.0.0:8093:8181' # calibre https
    restart: unless-stopped

  calibre-web:
    image: linuxserver/calibre-web:0.6.24
    container_name: calibre-web
    volumes:
      - /media/${USER}/Data/appdata/calibre-web:/config
      - /media/${USER}/Data/media/books:/books
    env_file:
      - stack.env
    network_mode: "service:transmission-openvpn"
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:v2-s6
    container_name: filebrowser
    volumes:
      - /media/${USER}/Data/appdata/filebrowser/filebrowser.db:/database/filebrowser.db
      - /media/${USER}/Data/appdata/filebrowser/settings.json:/config/settings.json
      # Shared folders root is /srv
      # After updating folders run: rm filebrowser.db ; touch filebrowser.db ; rm -rf ~/Applications/Filebrowser/* 
      - /home/${USER}/Applications/Filebrowser:/srv
      - /home/${USER}/Documents/Share:/srv/Documents
      - /media/${USER}/Backup/Share:/srv/Backup
    env_file:
      - stack.env
    ports:
      - '0.0.0.0:8090:80'
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:2.7.1
    container_name: lidarr
    volumes:
      - /media/${USER}/Data/appdata/lidarr:/config
      - /media/${USER}/Data/downloads:/downloads
      - /media/${USER}/Data/media:/media
    env_file:
      - stack.env
    network_mode: "service:transmission-openvpn"
    restart: unless-stopped

  openbooks:
    image: evanbuss/openbooks:4.5.0
    container_name: openbooks
    volumes:
      - /media/${USER}/Data/media/books_not_in_library:/books
    environment:
      - BASE_PATH=/openbooks/
    env_file:
      - stack.env
    network_mode: "service:transmission-openvpn"
    command: --name ${OPENBOOKS_DISPLAY_NAME} --persist
    restart: unless-stopped

  plex:
    image: linuxserver/plex:1.41.2
    container_name: plex
    volumes:
      - /media/${USER}/Data/appdata/plex:/config
      - /media/${USER}/Data/media/tv:/tv
      - /media/${USER}/Data/media/movies:/movies
      - /media/${USER}/Data/media/music:/music
    env_file:
      - stack.env
    ports:
      - '0.0.0.0:32400:32400' # plex
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:1.27.0
    container_name: prowlarr
    volumes:
      - /media/${USER}/Data/appdata/prowlarr:/config
    env_file:
      - stack.env
    network_mode: "service:transmission-openvpn"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:5.15.1
    container_name: radarr
    volumes:
      - /media/${USER}/Data/appdata/radarr:/config
      - /media/${USER}/Data/downloads:/downloads
      - /media/${USER}/Data/media:/media
    env_file:
      - stack.env
    network_mode: "service:transmission-openvpn"
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:4.0.11
    container_name: sonarr
    volumes:
      - /media/${USER}/Data/appdata/sonarr:/config
      - /media/${USER}/Data/downloads:/downloads
      - /media/${USER}/Data/media:/media
    env_file:
      - stack.env
    network_mode: "service:transmission-openvpn"
    restart: unless-stopped

  soulseek:
    image: realies/soulseek:tag
    container_name: soulseek
    volumes:
      - /media/${USER}/Data/appdata/soulseek:/data/.SoulseekQt
      - /media/${USER}/Data/downloads/soulseekqt:/data/Soulseek Downloads
      - /home/${USER}/.local/log/soulseek:/data/Soulseek Chat Logs # Shared folders
      - /media/${USER}/Data/media:/data/"Soulseek Shared Folder"
    env_file:
      - stack.env
    network_mode: "service:transmission-openvpn"
    restart: unless-stopped

  transmission-openvpn:
    image: haugene/transmission-openvpn:5.3.1
    container_name: transmission-openvpn
    volumes:
      - /media/${USER}/Data/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
      # May need to specify if using CUSTOM provider
      # - /home/${USER}/.secrets/{OPENVPN_CONFIG}.ovpn:/etc/openvpn/custom/{OPENVPN_CONFIG}.ovpn
    env_file:
      - stack.env
    ports:
      - '0.0.0.0:6080:6080' # soulseek
      - '0.0.0.0:7880:7878' # radarr 7878 used by SOAP
      # - '0.0.0.0:8092:8093'   # calibre
      # - '0.0.0.0:8093:8093'   # calibre
      - '0.0.0.0:8083:8083' # calibre-web
      - '0.0.0.0:8099:80' # openbooks
      - '0.0.0.0:8686:8686' # lidarr
      - '0.0.0.0:8888:8888'
      - '0.0.0.0:8989:8989' # sonarr
      - '0.0.0.0:9091:9091'
      # - '0.0.0.0:32400:32400' # plex
      - '0.0.0.0:9696:9696' # prowlarr
      - '0.0.0.0:51415:51413'
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
