name: "organizr"

services:
  organizr:
    image: organizr/organizr:linux-amd64
    container_name: organizr
    volumes:
      - /media/${USER}/Data/appdata/organizr:/config
    env_file:
      - stack.env
    ports:
      - '0.0.0.0:9983:80'
    restart: unless-stopped
