name: renovate

on:
  schedule:
    - cron: '0 0 */14 * *' # Runs every 2 weeks
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Create config file to allow "latest" and "dev" tags
      - name: Create config file
        run: |
          cat <<EOL > renovate.json
          {
          "extends": [
              "config:base"
          ],
          "docker": {
              "enabled": true
          }
          EOL
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v41.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
